### ISSUE TITLE
 issues or bugs with the project,

### ISSUE THREAD

**Issue by scarbear06** [king101-bit/DAVID#3]
Traceback (most recent call last):
  File "C:\Users\ENGINEER\Desktop\python\python\py files\DAVID-main\DAVID-main\main.py", line 60, in <module>
    str(track_phone_number(phone_number))
  File "C:\Users\ENGINEER\Desktop\python\python\py files\DAVID-main\DAVID-main\main.py", line 40, in track_phone_number
    area_code = phonenumbers.format_number(phonenumbers.parse(str(phone_number), "US"),phonenumbers.PhoneNUmberFormat.NATIONAL)[1:4]
  File "C:\Users\ENGINEER\Desktop\python\python\py files\DAVID-main\.venv\lib\site-packages\phonenumbers\phonenumberutil.py", line 2936, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.

**Comment by king101-bit** [comment]
Dear Scarbear06,

Thank you for bringing this to my attention. I will address the issue promptly and make the necessary corrections as soon as possible.

Best regards,

Zack

**Comment by king101-bit** [comment]
This is the format as the error above is caused by the phone number error.
Use this format: +1234567890
